[Main]
library=0
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=CONTINUA
Config=
ExtPrg=
Message=
Romid=200
Slot=0
Emu48Ram=C:\Archivos de programa\Hewlett-Packard\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Archivos de programa\Hewlett-Packard\Debug4x\Emu\default 48GX.bin
Emu49Ram=C:\Archivos de programa\Hewlett-Packard\Debug4x\Emu\default 49G.e49
FilePath=cntinua.hp
DirPath=CONTINUA
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=continua.S
[Edit]
edit1=>continua.S
