[Main]
library=0
AutoLoad=1
Compress=0
Calc48=1
KeepAll=0
UseDefaultEntryList=1
LoadOnly=0
EMUVisible=1
ProjectTab=0
InformHeight=50
EntryPointList=
Title=captura
Config=
ExtPrg=
Message=
Romid=200
Slot=0
Emu48Ram=D:\Mis Documentos\facultad\CDM\Taplicacion\grafica2.E48
Emu48Port2=C:\Archivos de programa\Hewlett-Packard\Debug4x\Emu\default 48GX.bin
Emu49Ram=C:\Archivos de programa\Hewlett-Packard\Debug4x\Emu\default 49G.e49
FilePath=grafico.hp
DirPath=captura
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=grafico.S
[Edit]
edit1=>grafico.S
edit2=C:\Archivos de programa\Hewlett-Packard\Debug4x\Include\Suprom48.a
